{
 "title": "GamblingDash",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "name_input_vidid", "label": "Video-ID", "query": "5MBwJpU-9tg" },
   { "name": "name_input_chid", "query": "UCmA-OmY_ZW7VZkET-64Psdg" }
  ]
 },
 "panels": [
  { "title": "Detection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  vc.author_name AS user,\n  yv.channel_name,\n  yv.title AS video_title,\n  vc.cleaned_text AS comment,\n  vc.published_at,\n  vc.is_gambling_promo\nFROM video_comments vc\nJOIN youtube_videos yv ON vc.video_id = yv.video_id\n-- WHERE vc.is_gambling_promo = false\nORDER BY vc.published_at DESC\nLIMIT 3000"
    }
   ]
  },
  {
   "title": "NER",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH words AS (\n  SELECT\n    regexp_split_to_table(LOWER(cleaned_text), '\\s+') AS word\n  FROM video_comments\n  WHERE\n    is_gambling_promo = true\n    --AND published_at >= NOW() - INTERVAL '24 HOURS'\n)\nSELECT\n  word,\n  COUNT(*) AS frequency\nFROM words\nWHERE LENGTH(word) BETWEEN 4 AND 20\n  AND word NOT IN ('yang', 'dengan', 'untuk', 'udah', 'kalo', 'tujuh', 'emang', 'bang','ngasih','nggak','sampe','beda','rela','best','rame','lgsng','bikin','jepe','bener-bener'\n  ,'sehat','game','main','orang','mulu','ortu','rumah','banget','ketagihan','salam','rezeki','menang','langsung','modal','cuan','coba','terbaik','hidup','kasih','dapet','modal','maen','auto',\n  'bilang','menang','keren','seru','mantap','gacir','gampang', 'konten','jepey','terima','join','temen','semangat','lancar','kayak', 'bermain')  -- Stopwords\nGROUP BY word\nHAVING COUNT(*) > 150 -- Menambahkan kondisi frekuensi lebih dari 200\nORDER BY frequency DESC\nLIMIT 21;"
    }
   ]
  },
  {
   "title": "Total Detected ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) \nFROM video_comments \nWHERE is_gambling_promo = true"
    }
   ]
  },
  {
   "title": "Top Gambling Promotor",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  author_name,\n  COUNT(*) AS kemunculan\nFROM\n  video_comments  WHERE is_gambling_promo = true\nGROUP BY\n  author_name\nORDER BY\n  kemunculan DESC;"
    }
   ]
  },
  {
   "title": "24H Trend",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH words AS (\n  SELECT \n    regexp_split_to_table(LOWER(cleaned_text), '\\s+') AS word\n  FROM video_comments\n  WHERE \n    is_gambling_promo = true\n    --AND published_at >= NOW() - INTERVAL '24 HOURS'\n)\nSELECT \n  word,\n  COUNT(*) AS frequency\nFROM words\nWHERE LENGTH(word) BETWEEN 4 AND 20\n  AND word NOT IN ('yang', 'dengan', 'untuk', 'udah', 'kalo', 'tujuh', 'emang', 'bang','ngasih','nggak','sampe','beda','rela','best','rame','lgsng'\n  ,'sehat','game','main','orang','mulu','ortu','rumah')  -- Stopwords\nGROUP BY word\nORDER BY frequency DESC\nLIMIT 1000;"
    }
   ]
  },
  {
   "title": "wordCloud | All",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "WITH \n-- Ekstrak kata dari komentar judi\ngambling_words AS (\n  SELECT \n    regexp_split_to_table(\n      regexp_replace(LOWER(cleaned_text), '[^\\w]+', ' ', 'g'),\n      '\\s+'\n    ) AS word,\n    comment_id\n  FROM video_comments\n  WHERE is_gambling_promo = false \n  AND LENGTH(cleaned_text) > 5\n),\n\n-- Filter kata umum (stopwords)\nfiltered_words AS (\n  SELECT word, COUNT(*) AS frequency\n  FROM gambling_words\n  WHERE \n    LENGTH(word) BETWEEN 4 AND 20\n    AND word NOT IN (\n      'yang', 'dengan', 'untuk', 'pada', 'dari', 'dan', 'di', 'ke', 'ini', 'itu'\n    )\n  GROUP BY word\n)\n\nSELECT word, frequency\nFROM filtered_words\nORDER BY frequency DESC\nLIMIT 500"
    }
   ]
  },
  {
   "title": "Prediksi Pertumbuhan Konten Judi",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "rawSql": "WITH daily_counts AS (\n  SELECT \n    DATE(published_at) AS date,\n    COUNT(*) AS gambling_comments\n  FROM video_comments\n  WHERE is_gambling_promo = true\n  GROUP BY date\n)\nSELECT\n  date,\n  gambling_comments,\n  AVG(gambling_comments) OVER (ORDER BY date ROWS BETWEEN 7 PRECEDING AND CURRENT ROW) AS moving_avg\nFROM daily_counts\nORDER BY date"
    }
   ]
  },
  {
   "title": "Gambling Detection Trend",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT DATE(published_at) as date, COUNT(*) as count \nFROM video_comments \nWHERE is_gambling_promo = true \nGROUP BY date \nORDER BY date"
    }
   ]
  },
  {
   "title": "Top Author",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  author_name,\n  COUNT(*) AS kemunculan\nFROM\n  video_comments\nGROUP BY\n  author_name\nORDER BY\n  kemunculan DESC;"
    }
   ]
  },
  {
   "title": "VideoData",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Viewer ",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT title, view_count \nFROM youtube_videos \nORDER BY view_count DESC \nLIMIT 10"
      }
     ]
    },
    {
     "title": "Top Detection by videos",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT yv.title, COUNT(vc.comment_id) as gambling_comments\nFROM video_comments vc\nJOIN youtube_videos yv ON vc.video_id = yv.video_id\nWHERE vc.is_gambling_promo = true\nGROUP BY yv.title\nORDER BY gambling_comments DESC\nLIMIT 10"
      }
     ]
    },
    {
     "title": "Gambling by Channel",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "rawSql": "SELECT \n  channel_name,\n  COUNT(DISTINCT yv.video_id) AS total_videos,\n  COUNT(DISTINCT CASE WHEN vc.is_gambling_promo = true THEN vc.comment_id END) AS gambling_comments,\n  COUNT(DISTINCT CASE WHEN vc.is_gambling_promo = true THEN vc.comment_id END) * 100.0 / \n    NULLIF(COUNT(DISTINCT vc.comment_id), 0) AS gambling_percentage\nFROM youtube_videos yv\nLEFT JOIN video_comments vc ON yv.video_id = vc.video_id\nGROUP BY channel_name\nORDER BY gambling_comments DESC\nLIMIT 10"
      }
     ]
    },
    {
     "title": "Videos By Channel",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "-- Total Channel Unik\nSELECT COUNT(DISTINCT channel_name) AS total_channels FROM youtube_videos;\n-- Total Video\nSELECT COUNT(*) AS total_videos FROM youtube_videos;"
      }
     ]
    }
   ]
  },
  { "title": "Engine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "auto scraper ch list",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "rawSql": "SELECT * FROM youtube_channels" }
   ]
  },
  {
   "title": "queque",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT * FROM scraping_queue ORDER BY created_at ASC"
    }
   ]
  },
  {
   "title": "LastScraped",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT video_id, created_at \nFROM scraping_queue \nORDER BY created_at DESC \nLIMIT 10"
    }
   ]
  },
  {
   "title": "Today Scraping",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT \n  DATE(scraped_at) AS scraping_date,\n  COUNT(*) AS videos_scraped\nFROM youtube_videos\nWHERE DATE(scraped_at) = CURRENT_DATE\nGROUP BY scraping_date;"
    }
   ]
  },
  {
   "title": "Scraping Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 47 },
   "targets": [
    {
     "rawSql": "SELECT DATE(scraped_at) as date, COUNT(*) as videos_scraped\nFROM youtube_videos\nGROUP BY date\nORDER BY date"
    }
   ]
  },
  {
   "title": "Channel ID",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "#http://192.168.88.254:15013/api/channelid",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"nama\": \"${name_input_chid}\"\n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Video ID",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "#http://192.168.88.254:15013/api/videoid",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"nama\": \"${name_input_vidid}\"\n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Video ID",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "parser": "backend",
     "source": "url",
     "type": "json",
     "url": "#http://192.168.88.254:15013/api/check",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"nama\": \"runcheck\"\n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  }
 ]
}